### ISSUE TITLE
permission error?

### ISSUE THREAD

**Issue by reishikin** [bnsantoso/sub-to-audio#1]
Hello, I was using your script but this error keeps appearing

using fairseq model as default
English is default language
 > tts_models/eng/fairseq/vits is already downloaded.
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
Traceback (most recent call last):
  File "C:\Users\WBstore\Desktop\22.py", line 19, in <module>
    subtitle = sub.subtitle(temp_subtitle_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WBstore\AppData\Local\Programs\Python\Python311\Lib\site-packages\subtoaudio\subtoaudio.py", line 40, in subtitle
    dictionary = self._extract_data_srt(temp_filename)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WBstore\AppData\Local\Programs\Python\Python311\Lib\site-packages\subtoaudio\subtoaudio.py", line 100, in _extract_data_srt
    with open(file_path, 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\WBstore\\AppData\\Local\\Temp\\tmppumq995a.srt'

**Comment by bnsantoso** [comment]
It is due to a temporary file already being open when creating it and trying to open it again, resulting in a permission error. Since I use Linux, I do not encounter this bug, sorry for this mistake. To work around it, I disabled auto delete, closed the file, and deleted it manually when the operation is done.

 edit the file `..\Python\Python311\Lib\site-packages\subtoaudio\subtoaudio.py` or just reinstall the package from git
```python
def subtitle(self, file_path:str):
    with tempfile.NamedTemporaryFile(suffix=".srt", delete=False) as temp_file:
      temp_filename = temp_file.name
      ffmpeg_command = f'ffmpeg -y -i "{file_path}" "{temp_filename}"'
      subprocess.run(ffmpeg_command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      temp_file.close()
      dictionary = self._extract_data_srt(temp_filename)
      os.unlink(temp_filename)
    return dictionary
```

if you encounter permission error again on audio section feel free to tell me

**Comment by reishikin** [comment]
Thank you so much for your prompt response! The permission error is no longer an issue, which is great. However, I'm now facing new challenges with longer SRT files (specifically, ones that are 2 hours long) and SRT files in different languages. I'll post these additional issues for further assistance. Thanks again for your help!
