### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by reishikin** [bnsantoso/sub-to-audio#4]
Edit: never mind. I found out the solution. I copied the config.json into the root directory of the virtual environment. Deleting this config.json solves it. 
===========
Hello, when I tried to use vie language subtitle, this error came up:

UnicodeDecodeError: 'cp932' codec can't decode byte 0x86 in position 253: illegal multibyte sequence
```

Here is my command
```
from subtoaudio import SubToAudio
sub = SubToAudio(model_path="G_100000.pth" , config_path="config.json")
subtitle = sub.subtitle("01.vi.srt")
sub.convert_to_audio(data=subtitle, tempo_mode="all", tempo_speed=1.3, lang="vie", output_path="01.vi.wav", save_temp=True,)
```

**Comment by bnsantoso** [comment]
i found UnicodeDecodeError when opening file. i dont know if this relate to your problem. 
`.../subtoaudio/subtoaudio.py`

fix: 
```python
#line 176
with open(file_path, 'r', encoding="utf-8") as file:
        file_content = file.read()
#...
#line 203
file.close()
return subtitle_data
```
i will add this change latter.
